package com.springboot.entity;

import java.io.Serializable;
import java.util.Date;

public class OrmUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user.id
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user.name
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user.password
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user.salt
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user.email
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user.phone_number
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user.status
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user.create_time
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user.last_login_time
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orm_user.last_update_time
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    private Date lastUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orm_user
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user.id
     *
     * @return the value of orm_user.id
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user.id
     *
     * @param id the value for orm_user.id
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user.name
     *
     * @return the value of orm_user.name
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user.name
     *
     * @param name the value for orm_user.name
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user.password
     *
     * @return the value of orm_user.password
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user.password
     *
     * @param password the value for orm_user.password
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user.salt
     *
     * @return the value of orm_user.salt
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user.salt
     *
     * @param salt the value for orm_user.salt
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user.email
     *
     * @return the value of orm_user.email
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user.email
     *
     * @param email the value for orm_user.email
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user.phone_number
     *
     * @return the value of orm_user.phone_number
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user.phone_number
     *
     * @param phoneNumber the value for orm_user.phone_number
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user.status
     *
     * @return the value of orm_user.status
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user.status
     *
     * @param status the value for orm_user.status
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user.create_time
     *
     * @return the value of orm_user.create_time
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user.create_time
     *
     * @param createTime the value for orm_user.create_time
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user.last_login_time
     *
     * @return the value of orm_user.last_login_time
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user.last_login_time
     *
     * @param lastLoginTime the value for orm_user.last_login_time
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orm_user.last_update_time
     *
     * @return the value of orm_user.last_update_time
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orm_user.last_update_time
     *
     * @param lastUpdateTime the value for orm_user.last_update_time
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", password=").append(password);
        sb.append(", salt=").append(salt);
        sb.append(", email=").append(email);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", lastLoginTime=").append(lastLoginTime);
        sb.append(", lastUpdateTime=").append(lastUpdateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}