package com.springboot.mapper;

import com.springboot.entity.OrmUser;
import com.springboot.entity.OrmUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    int countByExample(OrmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    int deleteByExample(OrmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    int insert(OrmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    int insertSelective(OrmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    List<OrmUser> selectByExample(OrmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    OrmUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    int updateByExampleSelective(@Param("record") OrmUser record, @Param("example") OrmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    int updateByExample(@Param("record") OrmUser record, @Param("example") OrmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    int updateByPrimaryKeySelective(OrmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orm_user
     *
     * @mbggenerated Thu Jul 16 15:07:53 CST 2020
     */
    int updateByPrimaryKey(OrmUser record);
}